spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/coupon
    username: root
    password: 123123
  jpa:
    generate-ddl: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    open-in-view: false

# docker pull mysql
# docker run -d -p 3307:3306 -e MYSQL_ROOT_PASSWORD=123123 --name mysql mysql